import Head from "next/head";

export default function Home() {
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${"dubai"}&appid=${
    process.env.NEXT_PUBLIC_WEATHER_KEY
  }`;
  return (
    <>
      <Head>
        <title>wheater - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
