import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import backgroundImage from "../public/earth-image.webp";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${"dubai"}&units=imperial&appid=${
    process.env.NEXT_PUBLIC_WEATHER_KEY
  }`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>wheater - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* overlay */}
      <div className="image__overlay" />
      {/* background image */}
      <BackgroundImage src={backgroundImage} />
      {/* search */}
      <div className="search__container">
        <form className="search__container--form">
          <div>
            <input className="search__container--input" type={"text"} placeholder="search city" />
          </div>
          <button onClick={fetchWeather}>
            <BsSearch />
          </button>
        </form>
      </div>
    </div>
  );
}

function BackgroundImage({ src }) {
  const divBgImage = {
    backgroundImage: `url(${src})`,
  };

  return <div className="backgroundDiv" style={divBgImage}></div>;
}
